import ApolloProviderComponent from './_components/ApolloProviderComponent';
import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* ApolloProvider는 클라이언트 환경에서만 사용할 수 있기 떄문에 component로 분리 */}
        <ApolloProviderComponent>
          <div className="navbar">
            <div>
              <Link href="/">Home</Link>
              <Link href="/restExample">REST</Link>
            </div>
            <div style={{ display: 'flex', alignItems: 'center' }}>
              <h3 style={{ color: '#757575', marginRight: '30px' }}>Graphql</h3>
              <Link href="/graphqlExample/graphqlMutation">Mutation</Link>
              <Link href="/graphqlExample/graphqlArgs">Args</Link>
              <Link href="/graphqlExample/graphqlMutitionInput">
                Mutation Input
              </Link>
              <Link href="/graphqlExample/graphqlMutationProduct">
                Mutation Product
              </Link>
            </div>
          </div>
          {children}
        </ApolloProviderComponent>
      </body>
    </html>
  );
}
